spring:
  application:
    name: edge-gateway
server:
  port: 8600
eureka:
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: true
  serviceUrl:
    defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
zuul:
  ignoredServices: '*'
  routes:
    product-service:
      path: /products/**
      service-id: product-service
    order-service:
      path: /orders/**
      service-id: order-service
    auth-service:
      path: /auth/**
      service-id: auth-service
      strip-prefix: true
      sensitive-headers: Cookie,Set-Cookie
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 3000