version: '3.9'
services:
  mongo_conatiner:
    image: mongo:latest
    environment:
      #      MONGO_INITDB_ROOT_USERNAME: root
      #      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: productdb
    ports:
      - 27017:27017
    volumes:
      - "/Volumes/Development/mongodb_12/db:/data/db"
      - "/Volumes/Development/mongodb_12/configdb:/data/configdb"
  rabbit:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbit-mq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "15672"
    depends_on:
      - mongo_conatiner
    environment:
      - CLUSTERED=true
      - RAM_NODE=true
      - CLUSTER_WITH=rabbit
      - RABBITMQ_DEFAULT_USER=bharat
      - RABBITMQ_DEFAULT_PASS=bharat

  discovery:
    build: discovery-service
    image: discovery-service:latest
    restart: on-failure
    ports:
      - 8761:8761
      - 18787:8787
    networks:
      - my_cloud_network

  order_ms:
    build: order-service
    image: order-service:latest
    restart: on-failure
    ports:
      - 8200:8200
      - 38787:8787
    depends_on:
      - discovery
    links:
      - discovery
      - mongo_conatiner
    networks:
      - my_cloud_network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/


  product_ms:
    build: product-service
    image: product-service:latest
    restart: on-failure
    ports:
      - 8300:8300
      - 28787:8787
    depends_on:
      - order_ms
      - discovery
      - mongo_conatiner
    links:
      - order_ms
      - discovery
      - mongo_conatiner
    networks:
      - my_cloud_network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/

  zuul-api-getway:
    build: api-getway
    image: api-getway:latest
    restart: on-failure
    ports:
      - 8600:8600
      - 8780:8787
    depends_on:
      - discovery
      - order_ms
      - product_ms
    links:
      - discovery
    networks:
    - my_cloud_network
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/

networks:
  my_cloud_network:
    driver: bridge