version: '3'
services:
  discovery:
    build: ./euraka-discovery
    networks:
    - my_cloud_network
    ports:
    - 8761:8761
    - 18787:8787
    restart: on-failure
  exchangerate:
    build: ./exchange-rates
    ports:
    - 8200:8200
    - 38787:8787
    depends_on:
    - discovery
    links:
    - discovery
    networks:
    - my_cloud_network
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    restart: on-failure
  converter:
    build: ./currency-converter
    ports:
    - 8300:8300
    - 28787:8787
    depends_on:
    - exchangerate
    - discovery
    links:
    - exchangerate
    - discovery
    networks:
    - my_cloud_network
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    restart: on-failure
  zuul-api-getway:
    build: ./zuul-api-getway
    ports:
    - 8600:8600
    - 8780:8787
    depends_on:
    - discovery
    - exchangerate
    - converter
    links:
    - discovery
    networks:
    - my_cloud_network
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    restart: on-failure
networks:
  my_cloud_network:
    driver: bridge