
zuul:
  routes:
    prodctService:
      path: /products/**
      service-id: product-service
    orderService:
      path: /orders/**
      service-id: order-service
#    authService:
#      path: /auth/**
#      service-id: auth-service
#      strip-prefix: true
#      sensitive-headers: Cookie,Set-Cookie